Adding CRN features for Migrate
prsadhu-ms-idc/azure-powershell pull request #50
Opened 2021-07-15 09:05 UTC by singhabh27

## Description

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

2021-07-21 06:38 UTC, prsadhu-ms-idc requested changes
LGTM. Minor nit comments added.

2021-07-21 06:38 UTC, prsadhu-ms-idc commented on src/Migrate/custom/New-AzMigrateNicMapping.ps1
> +            if ($TargetNicName.length -gt 80 -or $TargetNicName.length -eq 0) {
can it be null ?

2021-07-21 06:38 UTC, prsadhu-ms-idc commented on src/Migrate/custom/New-AzMigrateServerReplication.ps1
> +        if ($TargetVMName.length -gt 64 -or $TargetVMName.length -eq 0) {
Can it be null?

2021-07-21 06:38 UTC, prsadhu-ms-idc commented on src/Migrate/custom/New-AzMigrateServerReplication.ps1
> +             throw "The virtual machine name must be between 1 and 64 characters long."
target virtual machine

2021-07-21 06:38 UTC, prsadhu-ms-idc commented on src/Migrate/custom/New-AzMigrateServerReplication.ps1
> +             throw "The virtual machine name must be between 1 and 64 characters long."
everywhere else too.

2021-07-22 05:28 UTC, singhabh27 commented on src/Migrate/custom/New-AzMigrateServerReplication.ps1
> +        if ($TargetVMName.length -gt 64 -or $TargetVMName.length -eq 0) {
Yes, but it will throw error.

2021-07-22 05:28 UTC, singhabh27 commented on src/Migrate/custom/New-AzMigrateNicMapping.ps1
> +            if ($TargetNicName.length -gt 80 -or $TargetNicName.length -eq 0) {
Yes.

2021-07-22 09:54 UTC, singhabh27 commented on src/Migrate/custom/New-AzMigrateServerReplication.ps1
> +             throw "The virtual machine name must be between 1 and 64 characters long."
Done

2021-07-22 10:09 UTC, merged